Config = {}

Config.Weapons = {
    Pistols = {
        { title = 'Pistol', id = 'weapon_pistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_pistol' }, image = 'ox_inventory/web/images/WEAPON_PISTOL.png' },
        { title = 'Combat Pistol', id = 'weapon_combatpistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_combatpistol' }, image = 'ox_inventory/web/images/WEAPON_COMBATPISTOL.png' },
        { title = 'AP Pistol', id = 'weapon_appistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_appistol' }, image = 'ox_inventory/web/images/WEAPON_APPPISTOL.png' },
        { title = 'Stun Gun', id = 'weapon_stungun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_stungun' }, image = 'ox_inventory/web/images/WEAPON_STUNGUN.png' },
        { title = 'Pistol .50', id = 'weapon_pistol50', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_pistol50' }, image = 'ox_inventory/web/images/WEAPON_PISTOL50.png' },
        { title = 'SNS Pistol', id = 'weapon_snspistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_snspistol' }, image = 'ox_inventory/web/images/WEAPON_SNSPISTOL.png' },
        { title = 'Heavy Pistol', id = 'weapon_heavypistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_heavypistol' }, image = 'ox_inventory/web/images/WEAPON_HEAVYPISTOL.png' },
        { title = 'Vintage Pistol', id = 'weapon_vintagepistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_vintagepistol' }, image = 'ox_inventory/web/images/WEAPON_VINTAGEPISTOL.png' },
        { title = 'Flare Gun', id = 'weapon_flaregun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_flaregun' }, image = 'ox_inventory/web/images/WEAPON_FLAREGUN.png' },
        { title = 'Marksman Pistol', id = 'weapon_marksmanpistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_marksmanpistol' }, image = 'ox_inventory/web/images/WEAPON_MARKSMANPISTOL.png' },
        { title = 'Revolver', id = 'weapon_revolver', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_revolver' }, image = 'ox_inventory/web/images/WEAPON_REVOLVER.png' },
        { title = 'Double Action Revolver', id = 'weapon_doubleaction', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_doubleaction' }, image = 'ox_inventory/web/images/WEAPON_DOUBLEACTION.png' },
        { title = 'Ceramic Pistol', id = 'weapon_ceramicpistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_ceramicpistol' }, image = 'ox_inventory/web/images/WEAPON_CERAMICPISTOL.png' },
        { title = 'Navy Revolver', id = 'weapon_navyrevolver', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_navyrevolver' }, image = 'ox_inventory/web/images/WEAPON_NAVYREVOLVER.png' },
        { title = 'Perico Pistol', id = 'weapon_gadgetpistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_gadgetpistol' }, image = 'ox_inventory/web/images/WEAPON_GADGETPISTOL.png' },
        { title = 'Service Carbine', id = 'weapon_servicecarbine', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_servicecarbine' }, image = 'ox_inventory/web/images/WEAPON_SERVICECARBINE.png' }
    },
    SMGs = {
        { title = 'SMG', id = 'weapon_smg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_smg' }, image = 'ox_inventory/web/images/WEAPON_SMG.png' },
        { title = 'Micro SMG', id = 'weapon_microsmg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_microsmg' }, image = 'ox_inventory/web/images/WEAPON_MICROSMG.png' },
        { title = 'Assault SMG', id = 'weapon_assaultsmg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_assaultsmg' }, image = 'ox_inventory/web/images/WEAPON_ASSAULTSMG.png' },
        { title = 'Combat PDW', id = 'weapon_combatpdw', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_combatpdw' }, image = 'ox_inventory/web/images/WEAPON_COMBATPDW.png' },
        { title = 'Machine Pistol', id = 'weapon_machinepistol', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_machinepistol' }, image = 'ox_inventory/web/images/WEAPON_MACHINEPISTOL.png' },
        { title = 'Mini SMG', id = 'weapon_minismg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_minismg' }, image = 'ox_inventory/web/images/WEAPON_MINISMG.png' },
        { title = 'Unholy Hellbringer', id = 'weapon_raycarbine', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_raycarbine' }, image = 'ox_inventory/web/images/WEAPON_RAYCARBINE.png' }
    },
    Rifles = {
        { title = 'Assault Rifle', id = 'weapon_assaultrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_assaultrifle' }, image = 'ox_inventory/web/images/WEAPON_ASSAULTRIFLE.png' },
        { title = 'Carbine Rifle', id = 'weapon_carbinerifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_carbinerifle' }, image = 'ox_inventory/web/images/WEAPON_CARBINERIFLE.png' },
        { title = 'Advanced Rifle', id = 'weapon_advancedrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_advancedrifle' }, image = 'ox_inventory/web/images/WEAPON_ADVANCEDRIFLE.png' },
        { title = 'Special Carbine', id = 'weapon_specialcarbine', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_specialcarbine' }, image = 'ox_inventory/web/images/WEAPON_SPECIALCARBINE.png' },
        { title = 'Bullpup Rifle', id = 'weapon_bullpuprifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_bullpuprifle' }, image = 'ox_inventory/web/images/WEAPON_BULLPUPRIFLE.png' },
        { title = 'Compact Rifle', id = 'weapon_compactrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_compactrifle' }, image = 'ox_inventory/web/images/WEAPON_COMPACTRIFLE.png' },
        { title = 'Military Rifle', id = 'weapon_militaryrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_militaryrifle' }, image = 'ox_inventory/web/images/WEAPON_MILITARYRIFLE.png' },
        { title = 'Heavy Rifle', id = 'weapon_heavyrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_heavyrifle' }, image = 'ox_inventory/web/images/WEAPON_HEAVYRIFLE.png' },
        { title = 'Tactical Rifle', id = 'weapon_tacticalrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_tacticalrifle' }, image = 'ox_inventory/web/images/WEAPON_TACTICALRIFLE.png' }
    },
    SniperRifles = {
        { title = 'Sniper Rifle', id = 'weapon_sniperrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_sniperrifle' }, image = 'web/images/WEAPON_SNIPERRIFLE.png' },
        { title = 'Heavy Sniper', id = 'weapon_heavysniper', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_heavysniper' }, image = 'web/images/WEAPON_HEAVYSNIPER.png' },
        { title = 'Marksman Rifle', id = 'weapon_marksmanrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_marksmanrifle' }, image = 'web/images/WEAPON_MARKSMANRIFLE.png' },
        { title = 'Precision Rifle', id = 'weapon_precisionrifle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_precisionrifle' }, image = 'web/images/WEAPON_PRECISIONRIFLE.png' }
    },
    Shotguns = {
        { title = 'Pump Shotgun', id = 'weapon_pumpshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_pumpshotgun' }, image = 'web/images/WEAPON_PUMPSHOTGUN.png' },
        { title = 'Sawed-Off Shotgun', id = 'weapon_sawnoffshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_sawnoffshotgun' }, image = 'web/images/WEAPON_SAWNOFFSHOTGUN.png' },
        { title = 'Assault Shotgun', id = 'weapon_assaultshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_assaultshotgun' }, image = 'web/images/WEAPON_ASSAULTSHOTGUN.png' },
        { title = 'Bullpup Shotgun', id = 'weapon_bullpupshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_bullpupshotgun' }, image = 'web/images/WEAPON_BULLPUPSHOTGUN.png' },
        { title = 'Musket', id = 'weapon_musket', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_musket' }, image = 'web/images/WEAPON_MUSKET.png' },
        { title = 'Heavy Shotgun', id = 'weapon_heavyshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_heavyshotgun' }, image = 'web/images/WEAPON_HEAVYSHOTGUN.png' },
        { title = 'Double Barrel Shotgun', id = 'weapon_dbshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_dbshotgun' }, image = 'web/images/WEAPON_DBSHOTGUN.png' },
        { title = 'Sweeper Shotgun', id = 'weapon_autoshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_autoshotgun' }, image = 'web/images/WEAPON_AUTOSHOTGUN.png' },
        { title = 'Combat Shotgun', id = 'weapon_combatshotgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_combatshotgun' }, image = 'web/images/WEAPON_COMBATSHOTGUN.png' }
    },
    MachineGuns = {
        { title = 'MG', id = 'weapon_mg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_mg' }, image = 'ox_inventory/web/images/WEAPON_MG.png' },
        { title = 'Combat MG', id = 'weapon_combatmg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_combatmg' }, image = 'ox_inventory/web/images/WEAPON_COMBATMG.png' },
        { title = 'Gusenberg Sweeper', id = 'weapon_gusenberg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_gusenberg' }, image = 'ox_inventory/web/images/WEAPON_GUSENBERG.png' }
    },
    HeavyWeapons = {
        { title = 'RPG', id = 'weapon_rpg', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_rpg' }, image = 'ox_inventory/web/images/WEAPON_RPG.png' },
        { title = 'Grenade Launcher', id = 'weapon_grenadelauncher', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_grenadelauncher' }, image = 'ox_inventory/web/images/WEAPON_GRENADELAUNCHER.png' },
        { title = 'Minigun', id = 'weapon_minigun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_minigun' }, image = 'ox_inventory/web/images/WEAPON_MINIGUN.png' },
        { title = 'Firework Launcher', id = 'weapon_firework', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_firework' }, image = 'ox_inventory/web/images/WEAPON_FIREWORK.png' },
        { title = 'Railgun', id = 'weapon_railgun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_railgun' }, image = 'ox_inventory/web/images/WEAPON_RAILGUN.png' },
        { title = 'Homing Launcher', id = 'weapon_hominglauncher', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_hominglauncher' }, image = 'ox_inventory/web/images/WEAPON_HOMINGLAUNCHER.png' },
        { title = 'Compact Grenade Launcher', id = 'weapon_compactlauncher', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_compactlauncher' }, image = 'ox_inventory/web/images/WEAPON_COMPACTLAUNCHER.png' },
        { title = 'Widowmaker', id = 'weapon_rayminigun', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_rayminigun' }, image = 'ox_inventory/web/images/WEAPON_RAYMINIGUN.png' }
    },
    Throwables = {
        { title = 'Grenade', id = 'weapon_grenade', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_grenade' }, image = 'ox_inventory/web/images/WEAPON_GRENADE.png' },
        { title = 'Sticky Bomb', id = 'weapon_stickybomb', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_stickybomb' }, image = 'ox_inventory/web/images/WEAPON_STICKYBOMB.png' },
        { title = 'Proximity Mine', id = 'weapon_proxmine', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_proxmine' }, image = 'ox_inventory/web/images/WEAPON_PROXMINE.png' },
        { title = 'BZ Gas', id = 'weapon_bzgas', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_bzgas' }, image = 'ox_inventory/web/images/WEAPON_BZGAS.png' },
        { title = 'Molotov', id = 'weapon_molotov', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_molotov' }, image = 'ox_inventory/web/images/WEAPON_MOLOTOV.png' },
        { title = 'Fire Extinguisher', id = 'weapon_fireextinguisher', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_fireextinguisher' }, image = 'ox_inventory/web/images/WEAPON_FIREEXTINGUISHER.png' },
        { title = 'Petrol Can', id = 'weapon_petrolcan', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_petrolcan' }, image = 'ox_inventory/web/images/WEAPON_PETROLCAN.png' },
        { title = 'Flare', id = 'weapon_flare', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_flare' }, image = 'ox_inventory/web/images/WEAPON_FLARE.png' },
        { title = 'Ball', id = 'weapon_ball', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_ball' }, image = 'ox_inventory/web/images/WEAPON_BALL.png' },
        { title = 'Snowball', id = 'weapon_snowball', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_snowball' }, image = 'ox_inventory/web/images/WEAPON_SNOWBALL.png' },
        { title = 'Smoke Grenade', id = 'weapon_smokegrenade', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_smokegrenade' }, image = 'ox_inventory/web/images/WEAPON_SMOKEGRENADE.png' },
        { title = 'Pipe Bomb', id = 'weapon_pipebomb', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_pipebomb' }, image = 'ox_inventory/web/images/WEAPON_PIPEBOMB.png' }
    },
    Melee = {
        { title = 'Knife', id = 'weapon_knife', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_knife' }, image = 'ox_inventory/web/images/WEAPON_KNIFE.png' },
        { title = 'Nightstick', id = 'weapon_nightstick', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_nightstick' }, image = 'ox_inventory/web/images/WEAPON_NIGHTSTICK.png' },
        { title = 'Hammer', id = 'weapon_hammer', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_hammer' }, image = 'ox_inventory/web/images/WEAPON_HAMMER.png' },
        { title = 'Bat', id = 'weapon_bat', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_bat' }, image = 'ox_inventory/web/images/WEAPON_BAT.png' },
        { title = 'Crowbar', id = 'weapon_crowbar', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_crowbar' }, image = 'ox_inventory/web/images/WEAPON_CROWBAR.png' },
        { title = 'Golf Club', id = 'weapon_golfclub', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_golfclub' }, image = 'ox_inventory/web/images/WEAPON_GOLFCLUB.png' },
        { title = 'Bottle', id = 'weapon_bottle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_bottle' }, image = 'ox_inventory/web/images/WEAPON_BOTTLE.png' },
        { title = 'Dagger', id = 'weapon_dagger', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_dagger' }, image = 'ox_inventory/web/images/WEAPON_DAGGER.png' },
        { title = 'Hatchet', id = 'weapon_hatchet', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_hatchet' }, image = 'ox_inventory/web/images/WEAPON_HATCHET.png' },
        { title = 'Knuckle Duster', id = 'weapon_knuckle', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_knuckle' }, image = 'ox_inventory/web/images/WEAPON_KNUCKLE.png' },
        { title = 'Machete', id = 'weapon_machete', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_machete' }, image = 'ox_inventory/web/images/WEAPON_MACHETE.png' },
        { title = 'Flashlight', id = 'weapon_flashlight', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_flashlight' }, image = 'ox_inventory/web/images/WEAPON_FLASHLIGHT.png' },
        { title = 'Switchblade', id = 'weapon_switchblade', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_switchblade' }, image = 'ox_inventory/web/images/WEAPON_SWITCHBLADE.png' },
        { title = 'Pool Cue', id = 'weapon_poolcue', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_poolcue' }, image = 'ox_inventory/web/images/WEAPON_POOLCUE.png' },
        { title = 'Wrench', id = 'weapon_wrench', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_wrench' }, image = 'ox_inventory/web/images/WEAPON_WRENCH.png' },
        { title = 'Battle Axe', id = 'weapon_battleaxe', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_battleaxe' }, image = 'ox_inventory/web/images/WEAPON_BATTLEAXE.png' },
        { title = 'Stone Hatchet', id = 'weapon_stone_hatchet', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_stone_hatchet' }, image = 'ox_inventory/web/images/WEAPON_STONE_HATCHET.png' },
        { title = 'Candy Cane', id = 'weapon_candycane', event = 'ali-weaponmenu:selectWeapon', args = { 'weapon_candycane' }, image = 'ox_inventory/web/images/WEAPON_CANDYCANE.png' }
    },
    Custom = {
        { title = 'Ghost', id = 'w_pi_combatpistol', event = 'ali-weaponmenu:selectWeapon', args = { 'w_pi_combatpistol' } },
        { title = '38 Snub Nose', id = '38snubnose', event = 'ali-weaponmenu:selectWeapon', args = { '38snubnose' } },
        { title = '38 Snub Nose 2', id = 'w_pi_combatpistol', event = 'ali-weaponmenu:selectWeapon', args = { '38snubnose2' } },
        { title = '38 Snub Nose 3', id = '38snubnose3', event = 'ali-weaponmenu:selectWeapon', args = { '38snubnose3' } },
        { title = '38 Special', id = '38special', event = 'ali-weaponmenu:selectWeapon', args = { '38special' } },
        { title = '44 Magnum', id = '44magnum', event = 'ali-weaponmenu:selectWeapon', args = { '44magnum' } }
    }
}

Config.Components = {
    { title = 'Tactical Flashlight', id = 'at_flashlight', event = 'ali-weaponmenu:selectComponent', args = { 'at_flashlight' }, icon = 'fas fa-lightbulb' },
    { title = 'Suppressor', id = 'at_suppressor_light', event = 'ali-weaponmenu:selectComponent', args = { 'at_suppressor_light' }, icon = 'fas fa-volume-mute' },
    { title = 'Tactical Suppressor', id = 'at_suppressor_heavy', event = 'ali-weaponmenu:selectComponent', args = { 'at_suppressor_heavy' }, icon = 'fas fa-volume-mute' },
    { title = 'Grip', id = 'at_grip', event = 'ali-weaponmenu:selectComponent', args = { 'at_grip' }, icon = 'fas fa-hand-rock' },
    { title = 'Heavy Barrel', id = 'at_barrel', event = 'ali-weaponmenu:selectComponent', args = { 'at_barrel' }, icon = 'fas fa-weight-hanging' },
    { title = 'Extended Pistol Clip', id = 'at_clip_extended_pistol', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_extended_pistol' }, icon = 'fas fa-ellipsis-h' },
    { title = 'Extended SMG Clip', id = 'at_clip_extended_smg', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_extended_smg' }, icon = 'fas fa-ellipsis-h' },
    { title = 'Extended Shotgun Clip', id = 'at_clip_extended_shotgun', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_extended_shotgun' }, icon = 'fas fa-ellipsis-h' },
    { title = 'Extended Rifle Clip', id = 'at_clip_extended_rifle', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_extended_rifle' }, icon = 'fas fa-ellipsis-h' },
    { title = 'Extended MG Clip', id = 'at_clip_extended_mg', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_extended_mg' }, icon = 'fas fa-ellipsis-h' },
    { title = 'Extended Sniper Clip', id = 'at_clip_extended_sniper', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_extended_sniper' }, icon = 'fas fa-ellipsis-h' },
    { title = 'SMG Drum', id = 'at_clip_drum_smg', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_drum_smg' }, icon = 'fas fa-drum' },
    { title = 'Shotgun Drum', id = 'at_clip_drum_shotgun', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_drum_shotgun' }, icon = 'fas fa-drum' },
    { title = 'Rifle Drum', id = 'at_clip_drum_rifle', event = 'ali-weaponmenu:selectComponent', args = { 'at_clip_drum_rifle' }, icon = 'fas fa-drum' },
    { title = 'Compensator', id = 'at_compensator', event = 'ali-weaponmenu:selectComponent', args = { 'at_compensator' }, icon = 'fas fa-bolt' },
    { title = 'Macro Scope', id = 'at_scope_macro', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_macro' }, icon = 'fas fa-binoculars' },
    { title = 'Small Scope', id = 'at_scope_small', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_small' }, icon = 'fas fa-binoculars' },
    { title = 'Medium Scope', id = 'at_scope_medium', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_medium' }, icon = 'fas fa-binoculars' },
    { title = 'Large Scope', id = 'at_scope_large', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_large' }, icon = 'fas fa-binoculars' },
    { title = 'Advanced Scope', id = 'at_scope_advanced', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_advanced' }, icon = 'fas fa-binoculars' },
    { title = 'NV Scope', id = 'at_scope_nv', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_nv' }, icon = 'fas fa-eye-slash' },
    { title = 'Thermal Scope', id = 'at_scope_thermal', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_thermal' }, icon = 'fas fa-thermometer' },
    { title = 'Holographic Sight', id = 'at_scope_holo', event = 'ali-weaponmenu:selectComponent', args = { 'at_scope_holo' }, icon = 'fas fa-eye' },
    { title = 'Flat Muzzle', id = 'at_muzzle_flat', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_flat' }, icon = 'fas fa-bolt' },
    { title = 'Tactical Muzzle', id = 'at_muzzle_tactical', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_tactical' }, icon = 'fas fa-bolt' },
    { title = 'Fat Muzzle', id = 'at_muzzle_fat', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_fat' }, icon = 'fas fa-bolt' },
    { title = 'Precision Muzzle', id = 'at_muzzle_precision', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_precision' }, icon = 'fas fa-bolt' },
    { title = 'Heavy Muzzle', id = 'at_muzzle_heavy', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_heavy' }, icon = 'fas fa-bolt' },
    { title = 'Slanted Muzzle', id = 'at_muzzle_slanted', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_slanted' }, icon = 'fas fa-bolt' },
    { title = 'Split Muzzle', id = 'at_muzzle_split', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_split' }, icon = 'fas fa-bolt' },
    { title = 'Squared Muzzle', id = 'at_muzzle_squared', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_squared' }, icon = 'fas fa-bolt' },
    { title = 'Bell Muzzle', id = 'at_muzzle_bell', event = 'ali-weaponmenu:selectComponent', args = { 'at_muzzle_bell' }, icon = 'fas fa-bolt' }
}


Config.Modifications = {
    { title = 'Infinite Ammo', id = 'infinite_ammo', event = 'ali-weaponmenu:selectModification', args = { 'infinite_ammo' }, icon = 'fas fa-infinity' },
    { title = 'Reduce Recoil', id = 'reduce_recoil', event = 'ali-weaponmenu:selectModification', args = { 'reduce_recoil' }, icon = 'fas fa-compress-arrows-alt' },
    { title = 'Increased Damage', id = 'increased_damage', event = 'ali-weaponmenu:selectModification', args = { 'increased_damage' }, icon = 'fas fa-bomb' },
    { title = 'Faster Reload', id = 'faster_reload', event = 'ali-weaponmenu:selectModification', args = { 'faster_reload' }, icon = 'fas fa-tachometer-alt' },
    { title = 'Improved Accuracy', id = 'improved_accuracy', event = 'ali-weaponmenu:selectModification', args = { 'improved_accuracy' }, icon = 'fas fa-crosshairs' },
    { title = 'Fire Rate', id = 'fire_rate', event = 'ali-weaponmenu:selectModification', args = { 'fire_rate' }, icon = 'fas fa-bolt' },
    { title = 'Armor Piercing', id = 'armor_piercing', event = 'ali-weaponmenu:selectModification', args = { 'armor_piercing' }, icon = 'fas fa-shield-alt' },
    { title = 'Weapon Tints', id = 'weapon_tints', event = 'ali-weaponmenu:selectModification', args = { 'weapon_tints' }, icon = 'fas fa-palette' }
}

Config.Skins = {
    { title = 'Luxury Weapon Kit', id = 'at_skin_luxe', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_luxe' }, icon = 'fas fa-gem', description = 'Works on: Pistol, SMG, Rifle' },
    { title = 'Wood Weapon Kit', id = 'at_skin_wood', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_wood' }, icon = 'fas fa-tree', description = 'Works on: Shotgun, Sniper Rifle' },
    { title = 'Metal Weapon Kit', id = 'at_skin_metal', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_metal' }, icon = 'fas fa-industry', description = 'Works on: Pistol, SMG' },
    { title = 'Pearl Weapon Kit', id = 'at_skin_pearl', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_pearl' }, icon = 'fas fa-pearl', description = 'Works on: Rifle, Sniper Rifle' },
    { title = 'Ballas Weapon Kit', id = 'at_skin_ballas', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_ballas' }, icon = 'fas fa-skull', description = 'Works on: Pistol, SMG, Shotgun' },
    { title = 'Diamond Weapon Kit', id = 'at_skin_diamond', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_diamond' }, icon = 'fas fa-gem', description = 'Works on: Pistol, Rifle' },
    { title = 'Dollar Weapon Kit', id = 'at_skin_dollar', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_dollar' }, icon = 'fas fa-dollar-sign', description = 'Works on: SMG, Shotgun' },
    { title = 'Hate Weapon Kit', id = 'at_skin_hate', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_hate' }, icon = 'fas fa-heart-broken', description = 'Works on: Pistol, Rifle' },
    { title = 'King Weapon Kit', id = 'at_skin_king', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_king' }, icon = 'fas fa-crown', description = 'Works on: SMG, Sniper Rifle' },
    { title = 'Love Weapon Kit', id = 'at_skin_love', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_love' }, icon = 'fas fa-heart', description = 'Works on: Pistol, Shotgun' },
    { title = 'Pimp Weapon Kit', id = 'at_skin_pimp', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_pimp' }, icon = 'fas fa-hat-cowboy', description = 'Works on: SMG, Rifle' },
    { title = 'Player Weapon Kit', id = 'at_skin_player', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_player' }, icon = 'fas fa-user', description = 'Works on: Pistol, Sniper Rifle' },
    { title = 'Vagos Weapon Kit', id = 'at_skin_vagos', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_vagos' }, icon = 'fas fa-skull', description = 'Works on: SMG, Shotgun' },
    { title = 'Blagueurs Weapon Kit', id = 'at_skin_blagueurs', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_blagueurs' }, icon = 'fas fa-mask', description = 'Works on: Pistol, Rifle' },
    { title = 'Splatter Weapon Kit', id = 'at_skin_splatter', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_splatter' }, icon = 'fas fa-paint-brush', description = 'Works on: SMG, Sniper Rifle' },
    { title = 'Bullet Holes Weapon Kit', id = 'at_skin_bulletholes', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_bulletholes' }, icon = 'fas fa-bullseye', description = 'Works on: Pistol, Shotgun' },
    { title = 'Burger Shot Weapon Kit', id = 'at_skin_burgershot', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_burgershot' }, icon = 'fas fa-hamburger', description = 'Works on: SMG, Rifle' },
    { title = 'Cluckin Bell Weapon Kit', id = 'at_skin_cluckinbell', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_cluckinbell' }, icon = 'fas fa-drumstick-bite', description = 'Works on: Pistol, Sniper Rifle' },
    { title = 'Fatal Incursion Weapon Kit', id = 'at_skin_fatalincursion', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_fatalincursion' }, icon = 'fas fa-skull-crossbones', description = 'Works on: SMG, Shotgun' },
    { title = 'Lucha Libre Weapon Kit', id = 'at_skin_luchalibre', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_luchalibre' }, icon = 'fas fa-mask', description = 'Works on: Pistol, Rifle' },
    { title = 'Trippy Weapon Kit', id = 'at_skin_trippy', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_trippy' }, icon = 'fas fa-brain', description = 'Works on: SMG, Sniper Rifle' },
    { title = 'Tie-Dye Weapon Kit', id = 'at_skin_tiedye', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_tiedye' }, icon = 'fas fa-tshirt', description = 'Works on: Pistol, Shotgun' },
    { title = 'Wall Weapon Kit', id = 'at_skin_wall', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_wall' }, icon = 'fas fa-brick-wall', description = 'Works on: SMG, Rifle' },
    { title = 'VIP Weapon Kit', id = 'at_skin_vip', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_vip' }, icon = 'fas fa-user-tie', description = 'Works on: Pistol, Sniper Rifle' },
    { title = 'Bodyguard Weapon Kit', id = 'at_skin_bodyguard', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_bodyguard' }, icon = 'fas fa-shield-alt', description = 'Works on: SMG, Shotgun' },
    { title = 'Festive Weapon Kit', id = 'at_skin_festive', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_festive' }, icon = 'fas fa-snowflake', description = 'Works on: Pistol, Rifle' },
    { title = 'Security Weapon Kit', id = 'at_skin_security', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_security' }, icon = 'fas fa-lock', description = 'Works on: SMG, Sniper Rifle' },
    { title = 'Camo Weapon Kit', id = 'at_skin_camo', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_camo' }, icon = 'fas fa-camouflage', description = 'Works on: Pistol, Shotgun' },
    { title = 'Brushstroke Weapon Kit', id = 'at_skin_brushstroke', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_brushstroke' }, icon = 'fas fa-paint-brush', description = 'Works on: SMG, Rifle' },
    { title = 'Woodland Weapon Kit', id = 'at_skin_woodland', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_woodland' }, icon = 'fas fa-tree', description = 'Works on: Pistol, Sniper Rifle' },
    { title = 'Skull Weapon Kit', id = 'at_skin_skull', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_skull' }, icon = 'fas fa-skull', description = 'Works on: SMG, Shotgun' },
    { title = 'Sessanta Weapon Kit', id = 'at_skin_sessanta', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_sessanta' }, icon = 'fas fa-paint-brush', description = 'Works on: Pistol, Rifle' },
    { title = 'Perseus Weapon Kit', id = 'at_skin_perseus', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_perseus' }, icon = 'fas fa-paint-brush', description = 'Works on: SMG, Sniper Rifle' },
    { title = 'Leopard Weapon Kit', id = 'at_skin_leopard', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_leopard' }, icon = 'fas fa-paw', description = 'Works on: Pistol, Shotgun' },
    { title = 'Zebra Weapon Kit', id = 'at_skin_zebra', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_zebra' }, icon = 'fas fa-paw', description = 'Works on: SMG, Rifle' },
    { title = 'Geometric Weapon Kit', id = 'at_skin_geometric', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_geometric' }, icon = 'fas fa-shapes', description = 'Works on: Pistol, Sniper Rifle' },
    { title = 'Boom Weapon Kit', id = 'at_skin_boom', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_boom' }, icon = 'fas fa-bomb', description = 'Works on: SMG, Shotgun' },
    { title = 'Patriotic Weapon Kit', id = 'at_skin_patriotic', event = 'ali-weaponmenu:selectSkin', args = { 'at_skin_patriotic' }, icon = 'fas fa-flag-usa', description = 'Works on: Pistol, Rifle' }
}

